name: gallery_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_bloc: ^8.1.2
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+5
  dio: ^5.1.2
  build_runner: ^2.1.7
  json_annotation: ^4.8.1
  intl: ^0.18.1
  dotted_border: ^2.0.0+3
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0

flutter_icons:
  android: "launcher_icon"
  image_path_android: assets/images/gallery_launcher_logo_android.png
  ios: true
  remove_alpha_ios: true
  image_path_ios: assets/images/gallery_logo.png

flutter:
  assets:
    - assets/images/on_error.png
  uses-material-design: true
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
